import {Metadata} from "next";
import {Box, Paper, Stack, SvgIcon, Typography} from "@mui/material";
import Button from "@mui/material/Button";
import {ArrowDownOnSquareIcon, ArrowUpOnSquareIcon, PlusIcon} from "@heroicons/react/24/outline";
import React from "react";
import {CustomTabs} from "@/src/components/Tabs/tab";
import {SearchBar} from "@/src/components/search-bar";
import {SelectFilter} from "@/src/components/native-select";
import DataTable from "@/src/app/dashboard/admin/users/_components/roles-table";
export const metadata: Metadata = {
    title: 'Organization Members',
    description: 'Generated by create next app',
    // icons: {
    //     icon: 'logo-name.svg',
    // },
}

const tabNames = [
    {id: '1', name: 'All', value: 10},
    {id: '2', name: 'Dashboard', value: 10},
    {id: '3', name: 'API', value: 10},
    {id: '4', name: 'Mobile', value: 10},
    {id: '5', name: 'Devices', value: 10}
]

export default function Page() {
    return (
        <>
            <Stack spacing={3}>
                <Stack direction="row" justifyContent="space-between" spacing={4}>
                    <Stack spacing={1}>
                        <Typography variant="h4"> Organization Members</Typography>
                        <Stack alignItems="center" direction="row" spacing={1}>
                            <Button color="inherit" startIcon={(
                                <SvgIcon fontSize="small">
                                    <ArrowUpOnSquareIcon/>
                                </SvgIcon>
                            )}
                            >
                                Import
                            </Button>
                            <Button color="inherit" startIcon={(
                                <SvgIcon fontSize="small">
                                    <ArrowDownOnSquareIcon/>
                                </SvgIcon>
                            )}
                            >
                                Export
                            </Button>
                        </Stack>
                    </Stack>
                    <div>
                        <Button
                            startIcon={(
                                <SvgIcon fontSize="small">
                                    <PlusIcon/>
                                </SvgIcon>
                            )}
                            variant="contained"
                        >
                            Add
                        </Button>
                    </div>
                </Stack>
                <Paper elevation={3} sx={{borderRadius: 5}}>
                    <CustomTabs tabs={tabNames}/>
                    <Stack
                        direction={{xs: 'column', sm: 'row'}}
                        spacing={{xs: 1, sm: 2, md: 4}}
                        flexWrap="wrap"
                        sx={{display: 'flex', m: 2}}
                        alignItems='center'
                    >
                        <Box component="form" sx={{flexGrow: 1}}>
                            <SearchBar placeholderText={'Search Customer'} sx={{width: '100%'}}/>
                        </Box>
                        <SelectFilter/>
                    </Stack>
            <DataTable/>
                </Paper>
            </Stack>
        </>
    )
}