import {Metadata} from "next";


export const metadata: Metadata = {
    title: 'Theia Vision',
    description: 'Generated by create next app',
    // icons: {
    //     icon: 'logo-name.svg',
    // },
}

// backgroundColor:'#1e0050'
export default function Home() {
    return (
        <>
            {/*<NavBar/>*/}
            {/*<Box height={'100%'} component={'main'}>*/}

            {/*    /!*<Box alignItems={'center'} justifyContent={'center'} sx={{*!/*/}
            {/*    /!*    backgroundColor: '#1e0050', backgroundRepeat: 'no-repeat',*!/*/}
            {/*    /!*    backgroundPosition: 'center top', paddingTop: 16, color: '#fff'*!/*/}
            {/*    /!*}}>*!/*/}

            {/*    <Box alignItems={'center'} justifyContent={'center'} sx={{*/}
            {/*        backgroundImage: `url(/backgrounds/Theia-Vision_fundo-02.png)`, backgroundRepeat: 'repeat',*/}
            {/*        color: '#fff', backgroundPosition: 'center top',*/}
            {/*        backgroundSize: 'cover',paddingTop:7, paddingBottom:10,*/}
            {/*    }}>*/}
            {/*        <Section1/>*/}
            {/*    </Box>*/}

            {/*    <Box sx={{*/}
            {/*        backgroundImage: `url(/backgrounds/Theia-Vision_fundo-03.png)`, backgroundRepeat: 'no-repeat',*/}
            {/*        backgroundPosition: 'center top',*/}
            {/*        backgroundSize: 'cover', color: '#fff', paddingTop: 9, paddingBottom:16*/}

            {/*    }}>*/}
            {/*        <Section2/>*/}
            {/*    </Box>*/}

            {/*    <Box sx={{*/}
            {/*        backgroundImage: `url(/backgrounds/Theia-Vision_fundo-04.png)`, backgroundRepeat: 'no-repeat',*/}
            {/*        backgroundSize: 'cover', backgroundPosition: 'center top', paddingTop: 2, paddingBottom:14, color: '#fff'*/}
            {/*    }}>*/}
            {/*        <Section3/>*/}
            {/*    </Box>*/}

            {/*    <Box sx={{*/}
            {/*        backgroundImage: `url(/backgrounds/Theia-Vision_fundo-05.png)` , backgroundRepeat: 'no-repeat',*/}
            {/*        backgroundSize: 'cover', backgroundPosition: 'center top', paddingTop: 7, paddingBottom:13, color: '#fff'*/}
            {/*    }}>*/}
            {/*        <Section4/>*/}
            {/*    </Box>*/}

            {/*    <Box sx={{*/}
            {/*        backgroundImage: `url(/backgrounds/Theia-Vision_fundo-06.png)`, backgroundRepeat: 'no-repeat',*/}
            {/*        backgroundSize: 'cover', backgroundPosition: 'center top',paddingTop: 7, paddingBottom:14, color: '#fff'*/}
            {/*    }}>*/}
            {/*        <Section5/>*/}
            {/*        <Footer/>*/}
            {/*    </Box>*/}

            {/*</Box>*/}

        </>
    )
}