import {Metadata} from "next";
import {Stack, Typography} from "@mui/material";
import React from "react";
import Grid from "@mui/material/Unstable_Grid2";
import {MainCard, TicketsProps} from "@/app/dashboard/users/_components/overview/main-card";
import ChecklistRoundedIcon from "@mui/icons-material/ChecklistRounded";
import {UsageCard} from "@/app/dashboard/users/_components/overview/usage-card";

export const metadata: Metadata = {
    title: 'Dashboard',
    description: 'Generated by create next app',
}

const cardsContent: TicketsProps[] = [
    {
        icon: <ChecklistRoundedIcon/>,
        title: 'Tickets',
        value: 31,
        trend: 'up',
        percentage: 15,
    },
    {
        icon: <ChecklistRoundedIcon/>,
        title: 'Vehicles',
        value: 31,
        trend: 'up',
        percentage: 15,
    },
    {
        icon: <ChecklistRoundedIcon/>,
        title: 'Open Issues',
        value: 31,
        trend: 'up',
        percentage: 15,
    },
]
export default async function Dashboard() {
    return (
        <>
            <Stack gap={4}>
                <Typography component={'h4'} variant="h3">Overview</Typography>
                <Grid container spacing={4}>
                    {
                        cardsContent.map((card, index) =>
                            <Grid xs={12} md={4} key={index}>
                                <MainCard icon={card.icon} title={card.title} value={card.value} trend={card.trend}
                                          percentage={card.percentage}/>
                            </Grid>
                        )
                    }
                    <Grid xs={12} md={8}>
                        <UsageCard/>
                    </Grid>

                </Grid>
            </Stack>
        </>
    )
}